In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [ ]:
# load the data
df = pd.read_csv("Fatalities.csv")

# define the fatality rate
df["fatal_rate"] = df["fatal"] /df["pop"] * 10000

In [ ]:
df_demean = df.copy()

# calculate the entity(state) mean beer tax
df_demean['Mean_beerTax_byState'] = df_demean.groupby('state').beertax.transform(np.mean)

# calculate the entity(state) mean for fatal rate
df_demean['Mean_fatal_rate_byState'] = df_demean.groupby('state').fatal_rate.transform(np.mean)

In [8]:
df_demean

,Unnamed: 0,state,year,spirits,unemp,income,emppop,beertax,baptist,mormon,...,pop1517,pop1820,pop2124,milestot,unempus,emppopus,gsp,fatal_rate,Mean_beerTax_byState,Mean_fatal_rate_byState
0,1,al,1982,1.37,14.4,10544.152344,50.692039,-0.084413,30.355700,0.32829,...,208999.593750,221553.437500,290000.062500,28516.0,9.7,57.799999,-0.022125,-0.284267,1.623793,2.412627
1,2,al,1983,1.36,13.7,10732.797852,52.147030,0.165198,30.333599,0.34341,...,202000.078125,219125.468750,290000.156250,31032.0,9.6,57.900002,0.046558,-0.064147,1.623793,2.412627
2,3,al,1984,1.32,11.1,11108.791016,54.168087,0.090493,30.311501,0.35924,...,196999.968750,216724.093750,288000.156250,32961.0,7.5,59.500004,0.062798,-0.076197,1.623793,2.412627
3,4,al,1985,1.28,8.9,11332.626953,55.271137,0.028750,30.289499,0.37579,...,194999.734375,214349.031250,284000.312500,35091.0,7.2,60.100002,0.027490,-0.219147,1.623793,2.412627
4,5,al,1986,1.23,9.8,11661.506836,56.514496,-0.013886,30.267401,0.39311,...,203999.890625,212000.000000,263000.281250,36259.0,7.0,60.700001,0.032143,0.256513,1.623793,2.412627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,332,wy,1984,1.91,6.3,13456.043945,66.022095,0.001283,2.630720,8.55593,...,21999.941406,24821.398438,36999.839844,5127.0,7.5,59.500004,-0.016678,-0.157104,0.048168,3.217534
332,333,wy,1985,1.88,7.1,13595.338867,65.083801,-0.000498,2.720570,8.54494,...,22000.021484,24407.244141,35000.218750,5401.0,7.2,60.100002,-0.012126,-0.231284,0.048168,3.217534
333,334,wy,1986,1.70,9.0,13126.934570,63.966484,-0.001728,2.813500,8.53397,...,23000.005859,23999.998047,34999.789062,5384.0,7.0,60.700001,-0.109976,0.096076,0.048168,3.217534
334,335,wy,1987,1.59,8.6,12719.000000,62.857143,-0.003168,2.909600,8.52302,...,22000.021484,22999.916016,32999.671875,5367.0,6.2,61.500000,-0.123641,-0.584884,0.048168,3.217534
335,336,wy,1988,1.55,6.3,13098.170898,64.637680,-0.004857,3.008990,8.51208,...,21000.021484,20999.962891,30000.156250,5658.0,5.5,62.300003,-0.017023,0.018376,0.048168,3.217534

In [4]:
# demean, subtract each row by the entity-mean
df_demean["fatal_rate"] = df_demean["fatal_rate"] - df_demean['Mean_fatal_rate_byState']
df_demean["beertax"] = df_demean["beertax"] - df_demean['Mean_beerTax_byState']

model = sm.OLS(df_demean.fatal_rate, df_demean.beertax)
results2 = model.fit()
print(results2.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:             fatal_rate   R-squared (uncentered):                   0.041
Model:                            OLS   Adj. R-squared (uncentered):              0.038
Method:                 Least Squares   F-statistic:                              14.23
Date:                Fri, 07 Jul 2023   Prob (F-statistic):                    0.000191
Time:                        14:33:28   Log-Likelihood:                          107.97
No. Observations:                 336   AIC:                                     -213.9
Df Residuals:                     335   BIC:                                     -210.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
beertax       -0.6559      0.174     -3.772      0.000      -0.998      -0.314
==============================================================================
Omnibus:                       53.045   Durbin-Watson:                   1.517
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              219.863
Skew:                           0.585   Prob(JB):                     1.81e-48
Kurtosis:                       6.786   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.